package com.newportcapital.sia_erp.domain.model.sale_report.sale_report_item;

import com.newportcapital.sia_erp.domain.model.sale_report.SaleReportId;
import com.newportcapital.sia_erp.infrastructure.disposal_report.DisposalReportEntity;
import com.newportcapital.sia_erp.infrastructure.sale_report.SaleReportEntity;
import com.newportcapital.sia_erp.infrastructure.user.persistance.entity.UserEntity;

import java.time.LocalDateTime;

public class SaleReportItem {
    private SaleReportId id;
    private Float igv;
    private Float priceBase;
    private String approvalExit;
    private String approvalExitObservation;
    private String dispatch;
    private String dispatchObservation;
    private String inventoried;
    private String inventoriedObservation;
    private String delivered;
    private String deliveredObservation;
    private String status;
    private SaleReportEntity salesReportEntity;
    private DisposalReportEntity disposalReportEntity;
    private Integer approvalExitQuantity;
    private Integer dispatchQuantity;
    private Integer inventoriedQuantity;
    private String approvalExitQuantityObservation;
    private String dispatchQuantityObservation;
    private String quantityObservation;
    private Integer lastStock;
    private LocalDateTime creationDate;
    private LocalDateTime editionDate;
    private LocalDateTime approvalExitDate;
    private UserEntity approvalExitUserEntity;
    private LocalDateTime dispatchDate;
    private UserEntity dispatchUserEntity;
    private LocalDateTime revisionDate;
    private UserEntity revisionUserEntity;
    private LocalDateTime validationDate;
    private UserEntity validationUserEntity;
    private LocalDateTime approvalDate;
    private UserEntity approvalUserEntity;
    private LocalDateTime receptionDate;
    private UserEntity receptionUserEntity;
    private LocalDateTime approvalExitRejectionDate;
    private UserEntity approvalExitRejectionUserEntity;
    private LocalDateTime dispatchRejectionDate;
    private UserEntity dispatchRejectionUserEntity;
    private LocalDateTime revisionRejectionDate;
    private UserEntity revisionRejectionUserEntity;
    private LocalDateTime validationRejectionDate;
    private UserEntity validationRejectionUserEntity;
    private LocalDateTime approvalRejectionDate;
    private UserEntity approvalRejectionUserEntity;
    private LocalDateTime receptionRejectionDate;
    private UserEntity receptionRejectionUserEntity;

    public SaleReportItem(SaleReportId id, Float igv, Float priceBase, String approvalExit, String approvalExitObservation, String dispatch, String dispatchObservation, String inventoried, String inventoriedObservation, String delivered, String deliveredObservation, String status, SaleReportEntity salesReportEntity, DisposalReportEntity disposalReportEntity, Integer approvalExitQuantity, Integer dispatchQuantity, Integer inventoriedQuantity, String approvalExitQuantityObservation, String dispatchQuantityObservation, String quantityObservation, Integer lastStock, LocalDateTime creationDate, LocalDateTime editionDate, LocalDateTime approvalExitDate, UserEntity approvalExitUserEntity, LocalDateTime dispatchDate, UserEntity dispatchUserEntity, LocalDateTime revisionDate, UserEntity revisionUserEntity, LocalDateTime validationDate, UserEntity validationUserEntity, LocalDateTime approvalDate, UserEntity approvalUserEntity, LocalDateTime receptionDate, UserEntity receptionUserEntity, LocalDateTime approvalExitRejectionDate, UserEntity approvalExitRejectionUserEntity, LocalDateTime dispatchRejectionDate, UserEntity dispatchRejectionUserEntity, LocalDateTime revisionRejectionDate, UserEntity revisionRejectionUserEntity, LocalDateTime validationRejectionDate, UserEntity validationRejectionUserEntity, LocalDateTime approvalRejectionDate, UserEntity approvalRejectionUserEntity, LocalDateTime receptionRejectionDate, UserEntity receptionRejectionUserEntity) {
        this.id = id;
        this.igv = igv;
        this.priceBase = priceBase;
        this.approvalExit = approvalExit;
        this.approvalExitObservation = approvalExitObservation;
        this.dispatch = dispatch;
        this.dispatchObservation = dispatchObservation;
        this.inventoried = inventoried;
        this.inventoriedObservation = inventoriedObservation;
        this.delivered = delivered;
        this.deliveredObservation = deliveredObservation;
        this.status = status;
        this.salesReportEntity = salesReportEntity;
        this.disposalReportEntity = disposalReportEntity;
        this.approvalExitQuantity = approvalExitQuantity;
        this.dispatchQuantity = dispatchQuantity;
        this.inventoriedQuantity = inventoriedQuantity;
        this.approvalExitQuantityObservation = approvalExitQuantityObservation;
        this.dispatchQuantityObservation = dispatchQuantityObservation;
        this.quantityObservation = quantityObservation;
        this.lastStock = lastStock;
        this.creationDate = creationDate;
        this.editionDate = editionDate;
        this.approvalExitDate = approvalExitDate;
        this.approvalExitUserEntity = approvalExitUserEntity;
        this.dispatchDate = dispatchDate;
        this.dispatchUserEntity = dispatchUserEntity;
        this.revisionDate = revisionDate;
        this.revisionUserEntity = revisionUserEntity;
        this.validationDate = validationDate;
        this.validationUserEntity = validationUserEntity;
        this.approvalDate = approvalDate;
        this.approvalUserEntity = approvalUserEntity;
        this.receptionDate = receptionDate;
        this.receptionUserEntity = receptionUserEntity;
        this.approvalExitRejectionDate = approvalExitRejectionDate;
        this.approvalExitRejectionUserEntity = approvalExitRejectionUserEntity;
        this.dispatchRejectionDate = dispatchRejectionDate;
        this.dispatchRejectionUserEntity = dispatchRejectionUserEntity;
        this.revisionRejectionDate = revisionRejectionDate;
        this.revisionRejectionUserEntity = revisionRejectionUserEntity;
        this.validationRejectionDate = validationRejectionDate;
        this.validationRejectionUserEntity = validationRejectionUserEntity;
        this.approvalRejectionDate = approvalRejectionDate;
        this.approvalRejectionUserEntity = approvalRejectionUserEntity;
        this.receptionRejectionDate = receptionRejectionDate;
        this.receptionRejectionUserEntity = receptionRejectionUserEntity;
    }
}
